# Generated by Django 2.2 on 2021-12-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('female', 'женщина'), ('male', 'мужчина')], max_length=50)),
                ('avatar', models.ImageField(upload_to='djangopet/media/images')),
            ],
        ),
    ]
